SmartHomeMain/SmartHomeMVC/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SmartHomeMVC.Models;
using SmartHomeMain.DataLayer;

namespace SmartHomeMVC.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET: Houses
        [HttpGet]
        [Authorize(Roles = "Customer")]
        public ActionResult Index()
        {
            string customerId = db.Users.First(x => x.Email == User.Identity.Name).Id;
            var houses = db.Houses.Where(x => x.UserId == customerId).Include(h => h.City).Include(h => h.State);
            return View(houses.ToList());
        }

        // GET: Houses
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult CustomerHouses(string customerMail)
        {
            string customerId = db.Users.First(x => x.Email == customerMail).Id;
            var houses = db.Houses.Where(x=> x.UserId== customerId).Include(h => h.City).Include(h => h.State);
            ViewBag.CustomerId = customerId;
            return View(houses.ToList());
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // GET: Houses/Create
        public ActionResult Create(string customerId)
        {
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name");
            ViewBag.StateId = new SelectList(db.States, "Id", "Name");
            ViewBag.CustomerId = customerId;
            return View();
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ip,Port,DbName,Name,Address,Contact,UserId,CityId,StateId")] House house, string customerId)
        {
            if (ModelState.IsValid)
            {
                house.UserId = customerId;
                db.Houses.Add(house);
                db.SaveChanges();

                string customerEmail = db.Users.Find(customerId).Email;
                return RedirectToAction("CustomerHouses", new { customerMail=customerEmail});
            }

            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", house.CityId);
            ViewBag.StateId = new SelectList(db.States, "Id", "Name", house.StateId);
            return View(house);
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", house.CityId);
            ViewBag.StateId = new SelectList(db.States, "Id", "Name", house.StateId);
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ip,Port,DbName,Name,Address,Contact,UserId,CityId,StateId")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", house.CityId);
            ViewBag.StateId = new SelectList(db.States, "Id", "Name", house.StateId);
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SmartHomeMain/SmartHomeMVC/Views/Houses/Create.cshtml
@model SmartHomeMain.DataLayer.House

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>House</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Ip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DbName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DbName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DbName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CityId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" customerId="@ViewBag.CustomerId" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SmartHomeMain/SmartHomeMVC/Views/Houses/CustomerHouses.cshtml
@model IEnumerable<SmartHomeMain.DataLayer.House>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Houses", new { customerId=ViewBag.CustomerId}, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.City.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Port)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DbName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Port)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DbName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

SmartHomeMain/SmartHomeMVC/Views/Houses/Delete.cshtml
@model SmartHomeMain.DataLayer.House

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>House</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DbName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DbName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SmartHomeMain/SmartHomeMVC/Views/Houses/Details.cshtml
@model SmartHomeMain.DataLayer.House

@{
    ViewBag.Title = "Details";
    string houseIpPort = "127.0.0.1:80";
    if (ViewBag.HouseIpPort != null)
    {
        houseIpPort = ViewBag.HouseIpPort;
    }

}

<!-- FROM HERE -->
@section Scripts {
    @*@Scripts.Render("http://" + houseIpPort + "/SmartHomeInternal/Scripts/jquery.signalR-2.3.0.js")
    @Scripts.Render("http://" + houseIpPort + "/SmartHomeInternal/signalr/hubs")
    <script>
        $(document).ready(function () {
            var universalHub = $.connection.universalHub;

            if (universalHub != null) {
                universalHub.client.testCall = function (param1) {
                    // do something on client when called
                    alert(param1);
                };

                $.connection.hub.start().done(function () {
                    // something to do after connected successfully

                    universalHub.server.test();
                });
            }
            else {
                alert("SignalR hub not connected to " + "@houseIpPort" + "/SmartHomeInternal");
            }
        
        });
    </script>
    }*@
<!-- TO HERE -->

<h2>Details</h2>

<div>
    <h4>House</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Port)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Port)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DbName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DbName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SmartHomeMain/SmartHomeMVC/Views/Houses/Edit.cshtml
@model SmartHomeMain.DataLayer.House

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>House</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Ip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Port, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Port, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DbName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DbName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DbName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SmartHomeMain/SmartHomeMVC/Views/Houses/Index.cshtml
@model IEnumerable<SmartHomeMain.DataLayer.House>
<script src="~/Scripts/bootbox.min.js"></script>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div id="cont">
    <table class="table" id="hTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.City.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Port)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DbName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.City.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Port)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DbName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Devices", "Index", "Devices", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                    <input type="button" value="Devices" class="deviceBtn btn btn-info" data-param="@item.Ip" />
                </td>
            </tr>
        }

    </table>
</div>

<script>
    var ipAddress;

    var devBtns = document.getElementsByClassName("deviceBtn");
    for (i = 0; i < devBtns.length; i++) {
        devBtns[i].addEventListener('click', GetDevices, true);
    }
    function GetDevices(e) {
        var ip = e.target.dataset.param;
        ipAddress = ip;
        $.ajax(
            {
                type: "GET", //GET or POST or PUT or DELETE verb
                method: "GET",
                url: "http://" + ip + "/SmartHomeInternal/Service1.svc/Devices", // Location of the service
                contentType: "application/json; charset=utf-8", // content type sent to server
                dataType: "json", //Expected data format from server
                //processdata: true, //True or False
                success: function (msg) //On Successfull service call
                {
                    ShowSubscribeResult(msg);
                },
                error: function (jqXHR, textStatus, errorThrown) // When Service call fails
                {
                    alert(jqXHR);
                }
            }
        );
    }

    function ShowSubscribeResult(msg) {
        var table = document.getElementById("hTable");
        table.remove();

        var tDevices = document.createElement("table");
        tDevices.className = "table";

        var trHead = document.createElement("tr");
        var th1 = document.createElement("th");
        th1.innerText = "Name";
        trHead.appendChild(th1);
        var th2 = document.createElement("th");
        th2.innerText = "Type";
        trHead.appendChild(th2);
        var th3 = document.createElement("th");
        th3.innerText = "Registration date";
        trHead.appendChild(th3);
        tDevices.appendChild(trHead);

        let i = 0;
        for (i = 0; i < msg.length; i++) {
            var tr = document.createElement("tr");
            var td1 = document.createElement("td");
            td1.innerText = msg[i].Name;
            tr.appendChild(td1);
            var td2 = document.createElement("td");
            td2.innerText = msg[i].Type;
            tr.appendChild(td2);
            var td3 = document.createElement("td");
            td3.innerText = msg[i].DateOfRegStr;
            tr.appendChild(td3);

            var td4 = document.createElement("td");
            var bt = document.createElement("input");
            bt.type = "button";
            bt.value = "Show actions";
            bt.className = "btn btn-info";
            bt.dataset.actionList = JSON.stringify(msg[i].ActionList);
            bt.addEventListener('click', GetActions, true);
            td4.appendChild(bt);
            tr.appendChild(td4);

            var td5 = document.createElement("td");
            var bt1 = document.createElement("input");
            bt1.type = "button";
            bt1.value = "Show jobs";
            bt1.className = "btn btn-info";
            bt1.dataset.id = JSON.stringify(msg[i].Id);
            bt1.addEventListener('click', GetJobs, true);
            td5.appendChild(bt1);
            tr.appendChild(td5);
            tDevices.appendChild(tr);
        }

        var cont = document.getElementById("cont");
        cont.appendChild(tDevices);
    }

    function GetActions(e) {
        var actionList = JSON.parse(e.target.dataset.actionList);
        var result = "";
        let j = 0;
        for (j = 0; j < actionList.length; j++) {
            result += "Name: " + actionList[j].Name + " Repeatable: ";
            if (actionList[j].IsRepeatable)
                result += "Yes <br />";
            else
                result += "No <br />";
        }
        bootbox.confirm(result, function (result) { });
    }

    function GetJobs(e) {
        var id = e.target.dataset.id;
        $.ajax(
            {
                type: "GET", //GET or POST or PUT or DELETE verb
                method: "GET",
                url: "http://" + ipAddress + "/SmartHomeInternal/Service1.svc/DeviceInfo?id=" + id, // Location of the service
                contentType: "application/json; charset=utf-8", // content type sent to server
                dataType: "json", //Expected data format from server
                //processdata: true, //True or False
                success: function (msg) //On Successfull service call
                {
                    var jmsg = JSON.stringify(msg);
                    ShowJobs(jmsg);
                },
                error: function (jqXHR, textStatus, errorThrown) // When Service call fails
                {
                    alert(jqXHR);
                }
            }
        );
    }

    function ShowJobs(msg) {
        var test = JSON.parse(msg);
        var result = "";
        let i = 0;
        for (i = 0; i < test["ActionList"].length; i++) {
            result += "<h3>" + test.ActionList[i].Name + "</h3><br />"
            result += "<table class='table'>"
            result += "<thead class='thead-dark'>";
            result += "<tr> <th>Action</th> <th>Started</th> <th>Minutes repeat</th>  <th>Seconds repeat</th> </tr>";
            result += "</thead>";

            let j = 0;
            result += "<tbody>";
            for (j = 0; j < test.ActionList[i].JobList.length; j++) {
                result += "<tr>"

                result += "<td>" + test.ActionList[i].JobList[j].methodName + "</td>"; //Action

                result += "<td>";//Started
                if (test.ActionList[i].JobList[j].IsStarted)
                    result += "Yes ";
                else
                    result += "No ";
                result += "</td>";

                result += "<td>";//Minutes
                if (test.ActionList[i].JobList[j].repeatTimeMinutes != null)
                    result += test.ActionList[i].JobList[j].repeatTimeMinutes + " min ";
                else
                    result += "0 min ";
                result += "</td>";

                result += "<td>";//Seconds
                if (test.ActionList[i].JobList[j].repeatTimeSeconds != null)
                    result += test.ActionList[i].JobList[j].repeatTimeSeconds + "s ";
                else
                    result += "0 s ";
                result += "</td>";

                result += "<td>";
                debugger;
                if (test.ActionList[i].JobList[j].ReturnLogCount > 0) {
                    result += "<button class='btn btn-info' onclick='ReturnLog(" + test.ActionList[i].JobList[j].JobId + ")'><i class='fa fa-download'></i>" + "Download report </button>";
                }
                result += "</td>";

                result += " </tr>";
            }

            result += "</tbody>";
            result += "</table><br /></ br>"
        }

        bootbox.confirm(result, function (ds) { });
    }

    function ReturnLog(id) {
        $.ajax(
            {
                type: "GET", //GET or POST or PUT or DELETE verb
                method: "GET",
                url: "http://" + ipAddress + "/SmartHomeInternal/Service1.svc/JobInfo?id=" + id, // Location of the service
                contentType: "application/json; charset=utf-8", // content type sent to server
                dataType: "json", //Expected data format from server
                //processdata: true, //True or False
                success: function (msg) //On Successfull service call
                {
                    var jmsg = JSON.stringify(msg);
                    ShowLogs(jmsg);
                },
                error: function (jqXHR, textStatus, errorThrown) // When Service call fails
                {
                    alert(jqXHR);
                }
            }
        );
    }

    function ShowLogs(msg) {
        var test = JSON.parse(msg);
        if (test.ReturnLogList.length != 0) {
            var filepath = "Report";
            var columns = ["Value", "Time"];
            var data = new Array();
            let i;
            for (i = 0; i < test.ReturnLogList.length; i++) {
                var p = new Array();
                p.push(test.ReturnLogList[i].ReturnValue.toString());
                p.push(test.ReturnLogList[i].Time.toString());
                data.push(p);
            }
            var obj = {
                fileName: filepath,
                columns: columns,
                data: data
            };
            console.log(obj.data[0][0]);
            var str = JSON.stringify(obj);

            $.ajax(
                {
                    type: "POST", //GET or POST or PUT or DELETE verb
                    method: "POST",
                    //url: "http://localhost/ExcelTraining/api/Excel", // Location of the service
                    url: "http://172.22.183.95/api/Excel", // Location of the service
                    contentType: "application/json; charset=utf-8", // content type sent to server
                    //processdata: true, //True or False
                    data: str,
                    success: function () //On Successfull service call
                    {
                        GetData();
                    },
                    error: function (jqXHR, textStatus, errorThrown) // When Service call fails
                    {
                        alert(jqXHR);
                    }
                }
            );
        }
    }

    function GetData() {
        $.ajax({
            url: 'http://172.22.183.95/api/Excel',
            method: 'GET',
            xhrFields: {
                responseType: 'blob'
            },
            success: function (data) {
                var a = document.createElement('a');
                var url = window.URL.createObjectURL(data);
                a.href = url;
                a.download = 'Report.xlsx';
                a.click();
                window.URL.revokeObjectURL(url);
            }
        });
    }


</script>